apiVersion: v1
kind: Pod
metadata:
  name: mypod
  labels:
    run: mypod
spec:
  containers:
  - image: tamimibnaman/sit323_737-2023-t1-prac9p:latest
    name: sit323_737-2023-t1-prac9p
    ports:
    - containerPort: 8080
  dnsPolicy: ClusterFirst
  restartPolicy: Always