apiVersion: v1
kind: Pod
metadata:
  name: mypod
  labels:
    run: mypod
spec:
  containers:
  - image: sit323_737-2023-t1-prac9p:1.0
    name: prac9p
    ports:
    - containerPort: 8080
  dnsPolicy: ClusterFirst
  restartPolicy: Always