apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: prac9p
  labels:
    app: myapp
    tier: frontend
spec:
  # modify replicas according to your case
  replicas: 3
  selector:
    matchLabels:
      tier: frontend
  template:
    metadata:
      labels:
        tier: frontend
    spec:
      containers:
      - name: mynode
        image: sit323_737-2023-t1-prac9p:1.0
        ports:
        - containerPort: 8080